
import { GameMode, Locale } from './types';

export const RUSSIAN_ALPHABET = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ".split("");
export const UKRAINIAN_ALPHABET = "АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ".split("");
export const ENGLISH_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export const ALPHABET_BY_LOCALE: Record<Locale, string[]> = {
  ru: RUSSIAN_ALPHABET,
  uk: UKRAINIAN_ALPHABET,
  en: ENGLISH_ALPHABET,
  de: ENGLISH_ALPHABET,
  ro: ENGLISH_ALPHABET,
};

export const LOCALE_META: Record<Locale, { label: string; flag: string; shortLabel: string }> = {
  ru: { label: 'РУССКИЙ',    flag: '🇷🇺', shortLabel: 'RU' },
  en: { label: 'ENGLISH',    flag: '🇬🇧', shortLabel: 'EN' },
  uk: { label: 'УКРАЇНСЬКА', flag: '🇺🇦', shortLabel: 'UK' },
  de: { label: 'DEUTSCH',    flag: '🇩🇪', shortLabel: 'DE' },
  ro: { label: 'ROMÂNĂ',     flag: '🇷🇴', shortLabel: 'RO' },
};

export const DEFAULT_SETTINGS = {
  teamsCount: 2,
  teamNames: ["Team 1", "Team 2", "Team 3", "Team 4", "Team 5"],
  gameMode: GameMode.WITH_QUESTIONS,
  questionsTopic: "Bible Stories",
  levelSelectTimer: 5,
  answerTimer: 25,
  flipTimer: 15,
};

export const TRANSLATIONS = {
  ru: {
    close: "Закрыть",
    promptPageTitle: "Генератор Промпта",
    promptPageDesc: "Шаблон для мультиязычной генерации сложных вопросов в чат-ботах.",
    promptPageCopy: "КОПИРОВАТЬ",
    promptPageCopied: "Промпт скопирован!",
    title: "АЛФАВИТ",
    subtitle: "Интеллектуальная викторина.",
    start: "НАЧАТЬ ИГРУ",
    settings: "Настройки игры",
    mode: "Режим игры",
    withQuestions: "С ВОПРОСАМИ",
    withoutQuestions: "БЕЗ ВОПРОСОВ (MEMORY)",
    teamsCount: "Количество команд",
    teamNames: "Названия команд",
    activeSuite: "Активный набор",
    change: "Изменить",
    timers: "Таймеры",
    flipTimer: "Поиск пар (сек)",
    levelTimer: "Сложность (сек)",
    answerTimerLabel: "Ответ (сек)",
    aiGenerator: "ИИ ГЕНЕРАТОР",
    library: "БИБЛИОТЕКА",
    importJson: "ЗАГРУЗИТЬ JSON",
    guide: "РУКОВОДСТВО",
    prompt: "ПРОМПТ ДЛЯ ИИ",
    rules: "Правила игры",
    pause: "ПАУЗА",
    resume: "ПРОДОЛЖИТЬ",
    finish: "ЗАВЕРШИТЬ",
    turnOf: "ХОД КОМАНДЫ",
    team: "КОМАНДА",
    progress: "ПРОГРЕСС",
    correct: "ПРАВИЛЬНО!",
    wrong: "НЕВЕРНО!",
    rightAnswer: "Правильный ответ",
    check: "ПРОВЕРИТЬ",
    points: "баллов",
    victoryTitle: "Финал викторины!",
    leaderboard: "Итоговая таблица лидеров",
    mainMenu: "ГЛАВНОЕ МЕНЮ",
    back: "НАЗАД",
    home: "ДОМОЙ",
    complexity: {
      easy: "Легкий",
      medium: "Средний",
      hard: "Сложный"
    },
    levelFinished: "Вопросы закончились",
    allQuestionsFinished: "В этом наборе больше не осталось вопросов!",
    notSelected: "Не выбран",
    newSuite: "Новый набор",
    defaultTopic: "Библейские персонажи",
    suiteLoaded: (title: string) => `Набор «${title}» успешно загружен и активирован!`,
    invalidJson: "Ошибка: Неверный формат JSON",
    fileReadError: "Ошибка при чтении файла",
    turnTransition: "ХОД ПЕРЕХОДИТ К",
    chooseLevel: "Выберите сложность!",
    remaining: "Осталось: ",
    timeoutHint: "Если время выйдет, будет выбран доступный уровень.",
  },
  en: {
    close: "Close",
    promptPageTitle: "Prompt Generator",
    promptPageDesc: "Template for multilingual generation of complex Bible quiz questions in AI chat bots.",
    promptPageCopy: "COPY",
    promptPageCopied: "Prompt copied!",
    title: "ALPHABET",
    subtitle: "Intellectual Bible Quiz.",
    start: "START GAME",
    settings: "Game Settings",
    mode: "Game Mode",
    withQuestions: "WITH QUESTIONS",
    withoutQuestions: "MEMORY ONLY",
    teamsCount: "Number of Teams",
    teamNames: "Team Names",
    activeSuite: "Active Suite",
    change: "Change",
    timers: "Timers",
    flipTimer: "Flip Timer (sec)",
    levelTimer: "Level Timer (sec)",
    answerTimerLabel: "Answer Timer (sec)",
    aiGenerator: "AI GENERATOR",
    library: "LIBRARY",
    importJson: "IMPORT JSON",
    guide: "GUIDE",
    turnOf: "CURRENT TURN",
    team: "TEAM",
    prompt: "AI PROMPT",
    rules: "Game Rules",
    pause: "PAUSE",
    resume: "RESUME",
    finish: "FINISH",
    progress: "PROGRESS",
    correct: "CORRECT!",
    wrong: "WRONG!",
    rightAnswer: "Correct Answer",
    check: "CHECK",
    points: "points",
    complexity: {
      easy: "Easy",
      medium: "Medium",
      hard: "Hard"
    },
    victoryTitle: "Quiz Finished!",
    leaderboard: "Final Leaderboard",
    mainMenu: "MAIN MENU",
    back: "BACK",
    home: "HOME",
    levelFinished: "No more questions",
    allQuestionsFinished: "There are no more questions left in this suite!",
    notSelected: "Not selected",
    newSuite: "New Custom Suite",
    defaultTopic: "Bible Characters",
    suiteLoaded: (title: string) => `Suite «${title}» successfully loaded and activated!`,
    invalidJson: "Error: Invalid JSON format",
    fileReadError: "Error reading file",
    turnTransition: "TURN PASSES TO",
    chooseLevel: "Choose Difficulty!",
    remaining: "Left: ",
    timeoutHint: "If time runs out, an available level will be chosen.",
  },
  uk: {
    close: "Закрити",
    promptPageTitle: "Генератор Промпту",
    promptPageDesc: "Шаблон для багатомовної генерації складних запитань у чат-ботах.",
    promptPageCopy: "КОПІЮВАТИ",
    promptPageCopied: "Промпт скопійовано!",
    title: "АЛФАВІТ",
    subtitle: "Інтелектуальна вікторина.",
    start: "ПОЧАТИ ГРУ",
    settings: "Налаштування гри",
    mode: "Режим гри",
    withQuestions: "З ПИТАННЯМИ",
    withoutQuestions: "БЕЗ ПИТАНЬ (MEMORY)",
    teamsCount: "Кількість команд",
    teamNames: "Назви команд",
    activeSuite: "Активний набір",
    change: "Змінити",
    timers: "Таймери",
    flipTimer: "Пошук пар (сек)",
    levelTimer: "Складність (сек)",
    answerTimerLabel: "Відповідь (сек)",
    aiGenerator: "ІІ ГЕНЕРАТОР",
    library: "БІБЛІОТЕКА",
    importJson: "ЗАВАНТАЖИТИ JSON",
    guide: "ПОСІБНИК",
    prompt: "ПРОМПТ ДЛЯ ІІ",
    rules: "Правила гри",
    pause: "ПАУЗА",
    resume: "ПРОДОВЖИТИ",
    finish: "ЗАВЕРШИТИ",
    turnOf: "ХІД КОМАНДИ",
    team: "КОМАНДА",
    progress: "ПРОГРЕС",
    correct: "ПРАВИЛЬНО!",
    wrong: "НЕПРАВИЛЬНО!",
    rightAnswer: "Правильна відповідь",
    check: "ПЕРЕВІРИТИ",
    points: "балів",
    victoryTitle: "Фінал вікторини!",
    leaderboard: "Підсумкова таблиця лідерів",
    mainMenu: "ГОЛОВНЕ МЕНЮ",
    back: "НАЗАД",
    home: "ДОДОМУ",
    complexity: {
      easy: "Легкий",
      medium: "Середній",
      hard: "Складний"
    },
    levelFinished: "Питання закінчились",
    allQuestionsFinished: "У цьому наборі більше немає питань!",
    notSelected: "Не обрано",
    newSuite: "Новий набір",
    defaultTopic: "Біблійні персонажі",
    suiteLoaded: (title: string) => `Набір «${title}» успішно завантажено та активовано!`,
    invalidJson: "Помилка: Невірний формат JSON",
    fileReadError: "Помилка при читанні файлу",
    turnTransition: "ХІД ПЕРЕХОДИТЬ ДО",
    chooseLevel: "Оберіть складність!",
    remaining: "Залишилось: ",
    timeoutHint: "Якщо час вийде, буде обрано доступний рівень.",
  },
  de: {
    close: "Schließen",
    promptPageTitle: "Prompt-Generator",
    promptPageDesc: "Vorlage für die mehrsprachige Generierung komplexer Bibelquiz-Fragen in KI-Chatbots.",
    promptPageCopy: "KOPIEREN",
    promptPageCopied: "Prompt kopiert!",
    title: "ALPHABET",
    subtitle: "Intellektuelles Bibelquiz.",
    start: "SPIEL STARTEN",
    settings: "Spieleinstellungen",
    mode: "Spielmodus",
    withQuestions: "MIT FRAGEN",
    withoutQuestions: "NUR MEMORY",
    teamsCount: "Anzahl der Teams",
    teamNames: "Teamnamen",
    activeSuite: "Aktives Set",
    change: "Ändern",
    timers: "Timer",
    flipTimer: "Paare suchen (Sek)",
    levelTimer: "Schwierigkeit (Sek)",
    answerTimerLabel: "Antwort (Sek)",
    aiGenerator: "KI-GENERATOR",
    library: "BIBLIOTHEK",
    importJson: "JSON IMPORTIEREN",
    guide: "ANLEITUNG",
    prompt: "KI-PROMPT",
    rules: "Spielregeln",
    pause: "PAUSE",
    resume: "FORTSETZEN",
    finish: "BEENDEN",
    turnOf: "AKTUELLER ZUG",
    team: "TEAM",
    progress: "FORTSCHRITT",
    correct: "RICHTIG!",
    wrong: "FALSCH!",
    rightAnswer: "Richtige Antwort",
    check: "PRÜFEN",
    points: "Punkte",
    victoryTitle: "Quiz beendet!",
    leaderboard: "Abschlusstabelle",
    mainMenu: "HAUPTMENÜ",
    back: "ZURÜCK",
    home: "HOME",
    complexity: {
      easy: "Leicht",
      medium: "Mittel",
      hard: "Schwer"
    },
    levelFinished: "Keine weiteren Fragen",
    allQuestionsFinished: "Es gibt keine weiteren Fragen in diesem Set!",
    notSelected: "Nicht ausgewählt",
    newSuite: "Neues Frageset",
    defaultTopic: "Biblische Figuren",
    suiteLoaded: (title: string) => `Set «${title}» erfolgreich geladen und aktiviert!`,
    invalidJson: "Fehler: Ungültiges JSON-Format",
    fileReadError: "Fehler beim Lesen der Datei",
    turnTransition: "ZUG GEHT AN",
    chooseLevel: "Wähle Schwierigkeit!",
    remaining: "Verbleibend: ",
    timeoutHint: "Wenn die Zeit abläuft, wird ein verfügbares Level gewählt.",
  },
  ro: {
    close: "Închide",
    promptPageTitle: "Generator de Prompt",
    promptPageDesc: "Șablon pentru generarea multilingvă a întrebărilor complexe în chatboți AI.",
    promptPageCopy: "COPIAȚI",
    promptPageCopied: "Prompt copiat!",
    title: "ALFABET",
    subtitle: "Quiz Biblic Interactiv.",
    start: "ÎNCEPE JOCUL",
    settings: "Setările jocului",
    mode: "Modul de joc",
    withQuestions: "CU ÎNTREBĂRI",
    withoutQuestions: "DOAR MEMORY",
    teamsCount: "Numărul de echipe",
    teamNames: "Numele echipelor",
    activeSuite: "Set activ",
    change: "Schimbă",
    timers: "Timere",
    flipTimer: "Căutare perechi (sec)",
    levelTimer: "Dificultate (sec)",
    answerTimerLabel: "Răspuns (sec)",
    aiGenerator: "GENERATOR AI",
    library: "BIBLIOTECĂ",
    importJson: "IMPORTĂ JSON",
    guide: "GHID",
    prompt: "PROMPT AI",
    rules: "Regulile jocului",
    pause: "PAUZĂ",
    resume: "CONTINUĂ",
    finish: "TERMINĂ",
    turnOf: "RÂNDUL ECHIPEI",
    team: "ECHIPĂ",
    progress: "PROGRES",
    correct: "CORECT!",
    wrong: "GREȘIT!",
    rightAnswer: "Răspuns corect",
    check: "VERIFICĂ",
    points: "puncte",
    victoryTitle: "Finala quiz-ului!",
    leaderboard: "Clasament final",
    mainMenu: "MENIU PRINCIPAL",
    back: "ÎNAPOI",
    home: "ACASĂ",
    complexity: {
      easy: "Ușor",
      medium: "Mediu",
      hard: "Greu"
    },
    levelFinished: "Nu mai sunt întrebări",
    allQuestionsFinished: "Nu mai sunt întrebări în acest set!",
    notSelected: "Neselectat",
    newSuite: "Set nou de întrebări",
    defaultTopic: "Personaje biblice",
    suiteLoaded: (title: string) => `Setul «${title}» a fost încărcat și activat!`,
    invalidJson: "Eroare: Format JSON invalid",
    fileReadError: "Eroare la citirea fișierului",
    turnTransition: "RÂNDUL TRECE LA",
    chooseLevel: "Alege dificultatea!",
    remaining: "Rămase: ",
    timeoutHint: "Dacă timpul expiră, va fi ales un nivel disponibil.",
  },
};

export const COLORS = {
  primary: "#1e3a8a", 
  secondary: "#fbbf24", 
  accent: "#ef4444", 
  success: "#10b981", 
  background: "#f8fafc", 
};

export const SCORE_MATCH = 5;
export const SCORE_EASY = 3;
export const SCORE_MEDIUM = 6;
export const SCORE_HARD = 10;
