
import { GameMode, Locale } from './types';

export const RUSSIAN_ALPHABET = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ".split("");
export const UKRAINIAN_ALPHABET = "АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ".split("");
export const ENGLISH_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export const ALPHABET_BY_LOCALE: Record<Locale, string[]> = {
  ru: RUSSIAN_ALPHABET,
  uk: UKRAINIAN_ALPHABET,
  en: ENGLISH_ALPHABET,
  de: ENGLISH_ALPHABET,
  ro: ENGLISH_ALPHABET,
};

export const LOCALE_META: Record<Locale, { label: string; flag: string; shortLabel: string }> = {
  ru: { label: 'РУССКИЙ',    flag: '🇷🇺', shortLabel: 'RU' },
  en: { label: 'ENGLISH',    flag: '🇬🇧', shortLabel: 'EN' },
  uk: { label: 'УКРАЇНСЬКА', flag: '🇺🇦', shortLabel: 'UK' },
  de: { label: 'DEUTSCH',    flag: '🇩🇪', shortLabel: 'DE' },
  ro: { label: 'ROMÂNĂ',     flag: '🇷🇴', shortLabel: 'RO' },
};

export const DEFAULT_SETTINGS = {
  teamsCount: 2,
  teamNames: ["Team 1", "Team 2", "Team 3", "Team 4", "Team 5"],
  gameMode: GameMode.WITH_QUESTIONS,
  questionsTopic: "Bible Stories",
  levelSelectTimer: 5,
  answerTimer: 25,
  flipTimer: 15,
};

export const TRANSLATIONS = {
  ru: {
    rulesPage: {
      title: "Правила Игры",
      subtitle: "Интеллект • Память",
      section01Title: "Суть и Цель",
      section01Text: (cardCount: number, pairCount: number) =>
        `Игра объединяет классическую механику тренировки памяти и глубокую библейскую викторину. На поле расположены ${cardCount} карточек, скрывающих ${pairCount} пары букв алфавита. Ваша цель — найти как можно больше пар и закрепить успех правильными ответами на бонусные вопросы.`,
      section02Title: "Механика хода",
      section02Intro: "Команды ходят по очереди. В свой ход команда открывает две карточки.",
      matchTitle: "СОВПАДЕНИЕ:",
      matchItem1: (n: number) => `Счёт пополняется на +${n} баллов.`,
      matchItem2: "Карточки остаются открытыми.",
      matchItem3: "Команда получает БОНУСНЫЙ ВОПРОС.",
      matchItem4: "Ход остается у этой же команды!",
      missTitle: "ПРОМАХ:",
      missItem1: "Карточки закрываются через 1 секунду.",
      missItem2: "Баллы не начисляются.",
      missItem3: "Право хода переходит к следующей команде.",
      section03Title: "Система Начисления Очков",
      tableAction: "Действие",
      tableReward: "Награда",
      rowMatch: "Найдена пара букв",
      rowMatchPoints: (n: number) => `+${n} баллов`,
      rowEasy: "Бонусный вопрос: ЛЕГКИЙ",
      rowEasyPoints: (n: number) => `+${n} балла`,
      rowMedium: "Бонусный вопрос: СРЕДНИЙ",
      rowMediumPoints: (n: number) => `+${n} баллов`,
      rowHard: "Бонусный вопрос: СЛОЖНЫЙ",
      rowHardPoints: (n: number) => `+${n} баллов`,
      section04Title: "Бонусные Вопросы",
      section04Text: "После нахождения пары у команды есть шанс увеличить свой отрыв. Ведущий предлагает три уровня сложности.",
      section04Note: "Важно: на раздумья над выбором сложности дается 5-10 секунд. Если время выйдет, автоматически будет выбран ЛЕГКИЙ уровень. За неправильный ответ баллы не отнимаются, но команда теряет шанс на бонус.",
      finishTitle: "Финал игры",
      finishText: "Игра продолжается до тех пор, пока все карточки на поле не будут открыты. Победителем объявляется команда, набравшая наибольшее количество баллов в сумме (пары + бонусы).",
      mainMenuBtn: "В ГЛАВНОЕ МЕНЮ",
      openGuide: "Открыть гайд оператора",
    },
    guidePage: {
      title: "Мануал Ведущего",
      version: "v2.6 • Библиотека",
      grokTitle: "Генерация Вопросов",
      grokBadge: "PRO TIP",
      grokText: "Для создания уникальных наборов вопросов мы настоятельно рекомендуем использовать Grok AI. Это проверенный инструмент, который отлично понимает задачу.",
      grokSaveHint: "Как сохранить результат:",
      grokSaveText: (ext: string) =>
        `Скопируйте полученный от ИИ текст в обычный "Блокнот" на компьютере и при сохранении назовите файл, например, mygame${ext}. Самое главное — дописать в конце названия ${ext}, тогда игра сможет "прочитать" ваш файл.`,
      grokOpenBtn: "Открыть Grok.com",
      grokPromptBtn: "Взять Шаблон Промпта",
      section01Title: "Генерация и Языки",
      multiTitle: "Мультиязычность:",
      multiText: "Приложение поддерживает RU, EN, UK, DE, RO. Локаль набора отображается текстовым кодом. При выборе не-русского языка ИИ автоматически переключается на современные авторитетные переводы (ESV, NIV, Огиенко и др.).",
      multiTip: "Совет: При генерации на английском, вводите тему также на английском для лучшего результата.",
      aiTitle: "ИИ Управление:",
      aiText: "Вы можете в любой момент остановить генерацию, если заметили ошибку в теме или выбрали не тот язык.",
      aiBullet1: "Решайте капчу для подтверждения старта",
      aiBullet2: "200 вопросов создают огромную вариативность",
      section02Title: "Библиотека наборов",
      systemTitle: "Системные наборы (SYSTEM)",
      systemText: "Это золотой стандарт игры. Наборы по книгам Царств, Деяниям и Притчам всегда доступны и не могут быть удалены.",
      systemNote: "ОСОБЕННОСТЬ: Вы можете редактировать вопросы в системном наборе «в моменте», но после перезагрузки страницы он вернется к исходному состоянию.",
      userTitle: "Пользовательские (USER)",
      userText: "Наборы, которые вы создали через ИИ или импортировали из JSON-файлов. Они хранятся в памяти браузера, пока вы их не удалите.",
      section03Title: "Управление игрой",
      pauseTitle: "Пауза",
      pauseText: "Используйте кнопку паузы для перерывов. Экран игры будет заблюрен, а таймеры остановлены.",
      editorTitle: "Редактор",
      editorText: "Вы можете изменить любой вопрос прямо перед игрой. Изменения сохраняются только в активной сессии.",
      exportTitle: "Экспорт",
      exportText: "Нажмите на дискету в библиотеке, чтобы сохранить набор на диск. Это лучший способ не потерять свои вопросы.",
      section04Title: "Настройка Параметров Игры",
      section04Desc: "Все параметры настраиваются на экране перед стартом. Правильная настройка делает игру сбалансированной и динамичной.",
      settingsMode: "Режим игры",
      settingsModeWithQ: "С вопросами",
      settingsModeWithQDesc: "Классический режим: после каждого совпадения пары — бонусный вопрос. Команда зарабатывает дополнительные очки.",
      settingsModeMemory: "Только Memory",
      settingsModeMemoryDesc: "Игра без викторины — чистый поиск пар. Подходит для детей или быстрого раунда.",
      settingsSuite: "Набор вопросов",
      settingsSuiteDesc: "Выберите активный набор через Библиотеку. Набор можно сменить до старта или использовать ИИ-генератор для создания нового.",
      settingsTeams: "Команды",
      settingsTeamsDesc: "2–5 команд. Назовите каждую команду (до 20 символов) — имена отображаются на игровом табло.",
      settingsTimers: "Таймеры",
      settingsTimerFlip: "Поиск пар",
      settingsTimerFlipDesc: "5–60 сек. Время, в течение которого открытые карточки видны всем. Рекомендуется 10–15 сек для живой аудитории.",
      settingsTimerLevel: "Выбор сложности",
      settingsTimerLevelDesc: "3–30 сек. Время на принятие решения о сложности бонусного вопроса. Если истекает — автовыбор ЛЁГКОГО уровня.",
      settingsTimerAnswer: "Ответ на вопрос",
      settingsTimerAnswerDesc: "10–120 сек. Время на обсуждение и ответ. Для сложных тем рекомендуется 30–45 сек.",
      settingsStartTip: "Совет: Перед первой игрой попробуйте режим «Только Memory» для знакомства с механикой.",
      footerVersion: "v2.6 Stable / No-Flag Locale Engine",
      footerTagline: "Интеллектуальная игра \"Алфавит\" — инструмент для созидания и познания.",
    },
    close: "Закрыть",
    promptPageTitle: "Генератор Промпта",
    promptPageDesc: "Шаблон для мультиязычной генерации сложных вопросов в чат-ботах.",
    promptPageCopy: "КОПИРОВАТЬ",
    promptPageCopied: "Промпт скопирован!",
    title: "АЛФАВИТ",
    subtitle: "Интеллектуальная викторина.",
    start: "НАЧАТЬ ИГРУ",
    settings: "Настройки игры",
    mode: "Режим игры",
    withQuestions: "С ВОПРОСАМИ",
    withoutQuestions: "БЕЗ ВОПРОСОВ (MEMORY)",
    teamsCount: "Количество команд",
    teamNames: "Названия команд",
    activeSuite: "Активный набор",
    change: "Изменить",
    timers: "Таймеры",
    flipTimer: "Поиск пар (сек)",
    levelTimer: "Сложность (сек)",
    answerTimerLabel: "Ответ (сек)",
    aiGenerator: "ИИ ГЕНЕРАТОР",
    library: "БИБЛИОТЕКА",
    importJson: "ЗАГРУЗИТЬ JSON",
    guide: "РУКОВОДСТВО",
    prompt: "ПРОМПТ ДЛЯ ИИ",
    rules: "Правила игры",
    pause: "ПАУЗА",
    resume: "ПРОДОЛЖИТЬ",
    finish: "ЗАВЕРШИТЬ",
    turnOf: "ХОД КОМАНДЫ",
    team: "КОМАНДА",
    progress: "ПРОГРЕСС",
    correct: "ПРАВИЛЬНО!",
    wrong: "НЕВЕРНО!",
    rightAnswer: "Правильный ответ",
    check: "ПРОВЕРИТЬ",
    points: "баллов",
    victoryTitle: "Финал викторины!",
    leaderboard: "Итоговая таблица лидеров",
    mainMenu: "ГЛАВНОЕ МЕНЮ",
    back: "НАЗАД",
    home: "ДОМОЙ",
    complexity: {
      easy: "Легкий",
      medium: "Средний",
      hard: "Сложный"
    },
    levelFinished: "Вопросы закончились",
    allQuestionsFinished: "В этом наборе больше не осталось вопросов!",
    notSelected: "Не выбран",
    newSuite: "Новый набор",
    defaultTopic: "Библейские персонажи",
    suiteLoaded: (title: string) => `Набор «${title}» успешно загружен и активирован!`,
    invalidJson: "Ошибка: Неверный формат JSON",
    fileReadError: "Ошибка при чтении файла",
    turnTransition: "ХОД ПЕРЕХОДИТ К",
    chooseLevel: "Выберите сложность!",
    remaining: "Осталось: ",
    timeoutHint: "Если время выйдет, будет выбран доступный уровень.",
  },
  en: {
    rulesPage: {
      title: "Game Rules",
      subtitle: "Intelligence • Memory",
      section01Title: "Objective",
      section01Text: (cardCount: number, pairCount: number) =>
        `The game combines classic memory training mechanics with an in-depth Bible quiz. The board has ${cardCount} cards hiding ${pairCount} letter pairs. Your goal is to find as many pairs as possible and consolidate success by answering bonus questions correctly.`,
      section02Title: "Turn Mechanics",
      section02Intro: "Teams take turns. On each turn, a team flips two cards.",
      matchTitle: "MATCH:",
      matchItem1: (n: number) => `Score increases by +${n} points.`,
      matchItem2: "Cards remain face up.",
      matchItem3: "The team receives a BONUS QUESTION.",
      matchItem4: "The turn stays with the same team!",
      missTitle: "MISS:",
      missItem1: "Cards flip back after 1 second.",
      missItem2: "No points are awarded.",
      missItem3: "The turn passes to the next team.",
      section03Title: "Scoring System",
      tableAction: "Action",
      tableReward: "Reward",
      rowMatch: "Letter pair found",
      rowMatchPoints: (n: number) => `+${n} points`,
      rowEasy: "Bonus question: EASY",
      rowEasyPoints: (n: number) => `+${n} points`,
      rowMedium: "Bonus question: MEDIUM",
      rowMediumPoints: (n: number) => `+${n} points`,
      rowHard: "Bonus question: HARD",
      rowHardPoints: (n: number) => `+${n} points`,
      section04Title: "Bonus Questions",
      section04Text: "After finding a pair, the team has a chance to extend their lead. The host offers three difficulty levels.",
      section04Note: "Note: teams have 5–10 seconds to choose a difficulty. If time runs out, EASY is selected automatically. Wrong answers do not lose points, but the team loses the bonus opportunity.",
      finishTitle: "End of Game",
      finishText: "The game continues until all cards on the board are revealed. The team with the highest total score (pairs + bonuses) wins.",
      mainMenuBtn: "MAIN MENU",
      openGuide: "Open Operator Guide",
    },
    guidePage: {
      title: "Operator Guide",
      version: "v2.6 • Library",
      grokTitle: "Generating Questions",
      grokBadge: "PRO TIP",
      grokText: "To create unique question suites, we strongly recommend using Grok AI. It is a proven tool that understands the task well.",
      grokSaveHint: "How to save the result:",
      grokSaveText: (ext: string) =>
        `Copy the AI-generated text into a plain text editor (e.g. Notepad) and save the file with a name like mygame${ext}. The key step is to add ${ext} at the end of the filename so the game can read it.`,
      grokOpenBtn: "Open Grok.com",
      grokPromptBtn: "Get Prompt Template",
      section01Title: "Generation & Languages",
      multiTitle: "Multilingual Support:",
      multiText: "The app supports RU, EN, UK, DE, RO. The suite locale is shown as a text code. When selecting a non-Russian language, the AI automatically switches to authoritative modern translations (ESV, NIV, Ohienko, etc.).",
      multiTip: "Tip: When generating in English, enter the topic in English as well for best results.",
      aiTitle: "AI Controls:",
      aiText: "You can stop generation at any time if you notice a mistake in the topic or selected the wrong language.",
      aiBullet1: "Solve the CAPTCHA to confirm the start",
      aiBullet2: "150 questions provide huge variety for the quiz",
      section02Title: "Suite Library",
      systemTitle: "System Suites (SYSTEM)",
      systemText: "These are the gold standard of the game. Suites covering Kings, Acts, and Proverbs are always available and cannot be deleted.",
      systemNote: "NOTE: You can edit questions in a system suite mid-session, but after a page reload it will revert to its original state.",
      userTitle: "User Suites (USER)",
      userText: "Suites you created via AI or imported from JSON files. They are stored in the browser until you delete them.",
      section03Title: "Game Controls",
      pauseTitle: "Pause",
      pauseText: "Use the pause button for breaks. The game board will be blurred and timers will stop.",
      editorTitle: "Editor",
      editorText: "You can modify any question right before the game. Changes are saved for the current session only.",
      exportTitle: "Export",
      exportText: "Click the save icon in the library to download a suite to disk. This is the best way to keep your questions safe.",
      section04Title: "Game Settings",
      section04Desc: "All settings are configured on the pre-game screen. Correct setup makes the game balanced and engaging.",
      settingsMode: "Game Mode",
      settingsModeWithQ: "With Questions",
      settingsModeWithQDesc: "Classic mode: after each matched pair, the team answers a bonus question for extra points.",
      settingsModeMemory: "Memory Only",
      settingsModeMemoryDesc: "Pure memory game — no quiz. Great for children or a quick round.",
      settingsSuite: "Question Suite",
      settingsSuiteDesc: "Select the active suite from the Library. You can switch suites before the start or use the AI Generator to create a new one.",
      settingsTeams: "Teams",
      settingsTeamsDesc: "2–5 teams. Name each team (up to 20 characters) — names appear on the scoreboard.",
      settingsTimers: "Timers",
      settingsTimerFlip: "Flip search",
      settingsTimerFlipDesc: "5–60 sec. How long flipped cards stay visible. 10–15 sec is recommended for a live audience.",
      settingsTimerLevel: "Difficulty select",
      settingsTimerLevelDesc: "3–30 sec. Time to choose a bonus question difficulty. If it expires, EASY is selected automatically.",
      settingsTimerAnswer: "Answer time",
      settingsTimerAnswerDesc: "10–120 sec. Time to discuss and answer. 30–45 sec is recommended for harder topics.",
      settingsStartTip: "Tip: Before your first game, try Memory Only mode to get familiar with the mechanics.",
      footerVersion: "v2.6 Stable / No-Flag Locale Engine",
      footerTagline: "\"Alphabet\" — an intellectual game for learning and growth.",
    },
    close: "Close",
    promptPageTitle: "Prompt Generator",
    promptPageDesc: "Template for multilingual generation of complex Bible quiz questions in AI chat bots.",
    promptPageCopy: "COPY",
    promptPageCopied: "Prompt copied!",
    title: "ALPHABET",
    subtitle: "Intellectual Bible Quiz.",
    start: "START GAME",
    settings: "Game Settings",
    mode: "Game Mode",
    withQuestions: "WITH QUESTIONS",
    withoutQuestions: "MEMORY ONLY",
    teamsCount: "Number of Teams",
    teamNames: "Team Names",
    activeSuite: "Active Suite",
    change: "Change",
    timers: "Timers",
    flipTimer: "Flip Timer (sec)",
    levelTimer: "Level Timer (sec)",
    answerTimerLabel: "Answer Timer (sec)",
    aiGenerator: "AI GENERATOR",
    library: "LIBRARY",
    importJson: "IMPORT JSON",
    guide: "GUIDE",
    turnOf: "CURRENT TURN",
    team: "TEAM",
    prompt: "AI PROMPT",
    rules: "Game Rules",
    pause: "PAUSE",
    resume: "RESUME",
    finish: "FINISH",
    progress: "PROGRESS",
    correct: "CORRECT!",
    wrong: "WRONG!",
    rightAnswer: "Correct Answer",
    check: "CHECK",
    points: "points",
    complexity: {
      easy: "Easy",
      medium: "Medium",
      hard: "Hard"
    },
    victoryTitle: "Quiz Finished!",
    leaderboard: "Final Leaderboard",
    mainMenu: "MAIN MENU",
    back: "BACK",
    home: "HOME",
    levelFinished: "No more questions",
    allQuestionsFinished: "There are no more questions left in this suite!",
    notSelected: "Not selected",
    newSuite: "New Custom Suite",
    defaultTopic: "Bible Characters",
    suiteLoaded: (title: string) => `Suite «${title}» successfully loaded and activated!`,
    invalidJson: "Error: Invalid JSON format",
    fileReadError: "Error reading file",
    turnTransition: "TURN PASSES TO",
    chooseLevel: "Choose Difficulty!",
    remaining: "Left: ",
    timeoutHint: "If time runs out, an available level will be chosen.",
  },
  uk: {
    rulesPage: {
      title: "Правила Гри",
      subtitle: "Інтелект • Пам'ять",
      section01Title: "Суть і Мета",
      section01Text: (cardCount: number, pairCount: number) =>
        `Гра поєднує класичну механіку тренування пам'яті та глибоку біблійну вікторину. На полі розташовані ${cardCount} карток, що приховують ${pairCount} пари букв алфавіту. Ваша мета — знайти якомога більше пар та закріпити успіх правильними відповідями на бонусні запитання.`,
      section02Title: "Механіка ходу",
      section02Intro: "Команди ходять по черзі. У свій хід команда відкриває дві картки.",
      matchTitle: "ЗБІГ:",
      matchItem1: (n: number) => `Рахунок збільшується на +${n} балів.`,
      matchItem2: "Картки залишаються відкритими.",
      matchItem3: "Команда отримує БОНУСНЕ ЗАПИТАННЯ.",
      matchItem4: "Хід залишається у цієї ж команди!",
      missTitle: "ПРОМАХ:",
      missItem1: "Картки закриваються через 1 секунду.",
      missItem2: "Бали не нараховуються.",
      missItem3: "Право ходу переходить до наступної команди.",
      section03Title: "Система Нарахування Балів",
      tableAction: "Дія",
      tableReward: "Нагорода",
      rowMatch: "Знайдено пару букв",
      rowMatchPoints: (n: number) => `+${n} балів`,
      rowEasy: "Бонусне запитання: ЛЕГКЕ",
      rowEasyPoints: (n: number) => `+${n} бали`,
      rowMedium: "Бонусне запитання: СЕРЕДНЄ",
      rowMediumPoints: (n: number) => `+${n} балів`,
      rowHard: "Бонусне запитання: СКЛАДНЕ",
      rowHardPoints: (n: number) => `+${n} балів`,
      section04Title: "Бонусні Запитання",
      section04Text: "Після знаходження пари команда має шанс збільшити свій відрив. Ведучий пропонує три рівні складності.",
      section04Note: "Важливо: на роздуми над вибором складності дається 5-10 секунд. Якщо час вийде, автоматично буде вибрано ЛЕГКИЙ рівень. За неправильну відповідь бали не знімаються, але команда втрачає шанс на бонус.",
      finishTitle: "Фінал гри",
      finishText: "Гра продовжується доти, поки всі картки на полі не будуть відкриті. Переможцем оголошується команда, що набрала найбільшу кількість балів у сумі (пари + бонуси).",
      mainMenuBtn: "ГОЛОВНЕ МЕНЮ",
      openGuide: "Відкрити посібник оператора",
    },
    guidePage: {
      title: "Посібник Ведучого",
      version: "v2.6 • Бібліотека",
      grokTitle: "Генерація Запитань",
      grokBadge: "PRO TIP",
      grokText: "Для створення унікальних наборів запитань ми наполегливо рекомендуємо використовувати Grok AI. Це перевірений інструмент, який чудово розуміє завдання.",
      grokSaveHint: "Як зберегти результат:",
      grokSaveText: (ext: string) => `Скопіюйте отриманий від ІІ текст у звичайний "Блокнот" та при збереженні назвіть файл, наприклад, mygame${ext}. Найголовніше — дописати в кінці назви ${ext}.`,
      grokOpenBtn: "Відкрити Grok.com",
      grokPromptBtn: "Взяти Шаблон Промпту",
      section01Title: "Генерація та Мови",
      multiTitle: "Багатомовність:",
      multiText: "Додаток підтримує RU, EN, UK, DE, RO. Локаль набору відображається текстовим кодом.",
      multiTip: "Порада: При генерації англійською вводьте тему також англійською для кращого результату.",
      aiTitle: "Управління ІІ:",
      aiText: "Ви можете у будь-який момент зупинити генерацію, якщо помітили помилку в темі або вибрали не ту мову.",
      aiBullet1: "Вирішуйте капчу для підтвердження старту",
      aiBullet2: "150 запитань створюють величезну варіативність",
      section02Title: "Бібліотека наборів",
      systemTitle: "Системні набори (SYSTEM)",
      systemText: "Це золотий стандарт гри. Набори за книгами Царів, Діяннями та Приповістями завжди доступні і не можуть бути видалені.",
      systemNote: "ОСОБЛИВІСТЬ: Ви можете редагувати запитання в системному наборі «в моменті», але після перезавантаження сторінки він повернеться до початкового стану.",
      userTitle: "Користувацькі (USER)",
      userText: "Набори, які ви створили через ІІ або імпортували з JSON-файлів. Вони зберігаються в пам'яті браузера, поки ви їх не видалите.",
      section03Title: "Управління грою",
      pauseTitle: "Пауза",
      pauseText: "Використовуйте кнопку паузи для перерв. Екран гри буде розмитий, а таймери зупинені.",
      editorTitle: "Редактор",
      editorText: "Ви можете змінити будь-яке запитання прямо перед грою. Зміни зберігаються тільки в активній сесії.",
      exportTitle: "Експорт",
      exportText: "Натисніть на дискету в бібліотеці, щоб зберегти набір на диск. Це найкращий спосіб не втратити свої запитання.",
      section04Title: "Налаштування Параметрів Гри",
      section04Desc: "Усі параметри налаштовуються на екрані перед стартом.",
      settingsMode: "Режим гри",
      settingsModeWithQ: "З питаннями",
      settingsModeWithQDesc: "Класичний режим: після кожного збігу пари — бонусне питання. Команда заробляє додаткові бали.",
      settingsModeMemory: "Тільки Memory",
      settingsModeMemoryDesc: "Гра без вікторини — чистий пошук пар.",
      settingsSuite: "Набір питань",
      settingsSuiteDesc: "Оберіть активний набір через Бібліотеку.",
      settingsTeams: "Команди",
      settingsTeamsDesc: "2–5 команд. Назвіть кожну команду (до 20 символів).",
      settingsTimers: "Таймери",
      settingsTimerFlip: "Пошук пар",
      settingsTimerFlipDesc: "5–60 сек. Час, протягом якого відкриті картки видно всім.",
      settingsTimerLevel: "Вибір складності",
      settingsTimerLevelDesc: "3–30 сек. Час на вибір складності бонусного питання.",
      settingsTimerAnswer: "Відповідь на питання",
      settingsTimerAnswerDesc: "10–120 сек. Час на обговорення і відповідь.",
      settingsStartTip: "Порада: Перед першою грою спробуйте режим «Тільки Memory».",
      footerVersion: "v2.6 Stable / No-Flag Locale Engine",
      footerTagline: "Інтелектуальна гра \"Алфавіт\" — інструмент для творення і пізнання.",
    },
    close: "Закрити",
    promptPageTitle: "Генератор Промпту",
    promptPageDesc: "Шаблон для багатомовної генерації складних запитань у чат-ботах.",
    promptPageCopy: "КОПІЮВАТИ",
    promptPageCopied: "Промпт скопійовано!",
    title: "АЛФАВІТ",
    subtitle: "Інтелектуальна вікторина.",
    start: "ПОЧАТИ ГРУ",
    settings: "Налаштування гри",
    mode: "Режим гри",
    withQuestions: "З ПИТАННЯМИ",
    withoutQuestions: "БЕЗ ПИТАНЬ (MEMORY)",
    teamsCount: "Кількість команд",
    teamNames: "Назви команд",
    activeSuite: "Активний набір",
    change: "Змінити",
    timers: "Таймери",
    flipTimer: "Пошук пар (сек)",
    levelTimer: "Складність (сек)",
    answerTimerLabel: "Відповідь (сек)",
    aiGenerator: "ІІ ГЕНЕРАТОР",
    library: "БІБЛІОТЕКА",
    importJson: "ЗАВАНТАЖИТИ JSON",
    guide: "ПОСІБНИК",
    prompt: "ПРОМПТ ДЛЯ ІІ",
    rules: "Правила гри",
    pause: "ПАУЗА",
    resume: "ПРОДОВЖИТИ",
    finish: "ЗАВЕРШИТИ",
    turnOf: "ХІД КОМАНДИ",
    team: "КОМАНДА",
    progress: "ПРОГРЕС",
    correct: "ПРАВИЛЬНО!",
    wrong: "НЕПРАВИЛЬНО!",
    rightAnswer: "Правильна відповідь",
    check: "ПЕРЕВІРИТИ",
    points: "балів",
    victoryTitle: "Фінал вікторини!",
    leaderboard: "Підсумкова таблиця лідерів",
    mainMenu: "ГОЛОВНЕ МЕНЮ",
    back: "НАЗАД",
    home: "ДОДОМУ",
    complexity: {
      easy: "Легкий",
      medium: "Середній",
      hard: "Складний"
    },
    levelFinished: "Питання закінчились",
    allQuestionsFinished: "У цьому наборі більше немає питань!",
    notSelected: "Не обрано",
    newSuite: "Новий набір",
    defaultTopic: "Біблійні персонажі",
    suiteLoaded: (title: string) => `Набір «${title}» успішно завантажено та активовано!`,
    invalidJson: "Помилка: Невірний формат JSON",
    fileReadError: "Помилка при читанні файлу",
    turnTransition: "ХІД ПЕРЕХОДИТЬ ДО",
    chooseLevel: "Оберіть складність!",
    remaining: "Залишилось: ",
    timeoutHint: "Якщо час вийде, буде обрано доступний рівень.",
  },
  de: {
    rulesPage: {
      title: "Spielregeln",
      subtitle: "Intelligenz • Gedächtnis",
      section01Title: "Ziel des Spiels",
      section01Text: (cardCount: number, pairCount: number) =>
        `Das Spiel verbindet klassisches Gedächtnistraining mit einem tiefgründigen Bibelquiz. Das Spielfeld hat ${cardCount} Karten mit ${pairCount} Buchstabenpaaren. Ihr Ziel ist es, so viele Paare wie möglich zu finden und durch richtige Bonusfragen zu punkten.`,
      section02Title: "Spielzugmechanik",
      section02Intro: "Teams spielen abwechselnd. In einem Zug dreht ein Team zwei Karten um.",
      matchTitle: "TREFFER:",
      matchItem1: (n: number) => `Punktzahl erhöht sich um +${n} Punkte.`,
      matchItem2: "Karten bleiben offen.",
      matchItem3: "Das Team erhält eine BONUSFRAGE.",
      matchItem4: "Der Zug bleibt beim selben Team!",
      missTitle: "FEHLSCHLAG:",
      missItem1: "Karten werden nach 1 Sekunde umgedreht.",
      missItem2: "Keine Punkte werden vergeben.",
      missItem3: "Der Zug geht an das nächste Team.",
      section03Title: "Punktesystem",
      tableAction: "Aktion",
      tableReward: "Belohnung",
      rowMatch: "Buchstabenpaar gefunden",
      rowMatchPoints: (n: number) => `+${n} Punkte`,
      rowEasy: "Bonusfrage: LEICHT",
      rowEasyPoints: (n: number) => `+${n} Punkte`,
      rowMedium: "Bonusfrage: MITTEL",
      rowMediumPoints: (n: number) => `+${n} Punkte`,
      rowHard: "Bonusfrage: SCHWER",
      rowHardPoints: (n: number) => `+${n} Punkte`,
      section04Title: "Bonusfragen",
      section04Text: "Nach dem Finden eines Paares hat das Team die Chance, seinen Vorsprung zu vergrößern. Der Moderator bietet drei Schwierigkeitsstufen an.",
      section04Note: "Hinweis: Teams haben 5–10 Sekunden für die Auswahl. Läuft die Zeit ab, wird automatisch LEICHT gewählt. Falsche Antworten kosten keine Punkte, aber das Team verliert den Bonusvorteil.",
      finishTitle: "Spielende",
      finishText: "Das Spiel läuft, bis alle Karten aufgedeckt sind. Das Team mit der höchsten Gesamtpunktzahl (Paare + Boni) gewinnt.",
      mainMenuBtn: "HAUPTMENÜ",
      openGuide: "Spielleiteranleitung öffnen",
    },
    guidePage: {
      title: "Spielleiteranleitung",
      version: "v2.6 • Bibliothek",
      grokTitle: "Fragen generieren",
      grokBadge: "PRO TIP",
      grokText: "Zur Erstellung einzigartiger Fragensätze empfehlen wir dringend Grok AI. Es ist ein bewährtes Tool, das die Aufgabe gut versteht.",
      grokSaveHint: "So speichern Sie das Ergebnis:",
      grokSaveText: (ext: string) => `Kopieren Sie den KI-generierten Text in einen Texteditor und speichern Sie die Datei als mygame${ext}. Wichtig: Die Erweiterung ${ext} am Ende des Dateinamens hinzufügen.`,
      grokOpenBtn: "Grok.com öffnen",
      grokPromptBtn: "Prompt-Vorlage holen",
      section01Title: "Generierung & Sprachen",
      multiTitle: "Mehrsprachigkeit:",
      multiText: "Die App unterstützt RU, EN, UK, DE, RO. Das Gebietsschema des Satzes wird als Textcode angezeigt.",
      multiTip: "Tipp: Geben Sie beim Generieren auf Englisch auch das Thema auf Englisch ein.",
      aiTitle: "KI-Steuerung:",
      aiText: "Sie können die Generierung jederzeit stoppen, wenn Sie einen Fehler im Thema bemerken.",
      aiBullet1: "CAPTCHA lösen, um den Start zu bestätigen",
      aiBullet2: "150 Fragen bieten eine enorme Vielfalt",
      section02Title: "Fragebibliothek",
      systemTitle: "Systemsätze (SYSTEM)",
      systemText: "Dies ist der Goldstandard des Spiels. Sätze zu Könige, Apostelgeschichte und Sprüche sind immer verfügbar und können nicht gelöscht werden.",
      systemNote: "HINWEIS: Sie können Fragen in einem Systemsatz in der aktuellen Sitzung bearbeiten, aber nach einem Neuladen kehrt er zum Originalzustand zurück.",
      userTitle: "Benutzersätze (USER)",
      userText: "Sätze, die Sie über KI erstellt oder aus JSON-Dateien importiert haben. Sie werden im Browser gespeichert, bis Sie sie löschen.",
      section03Title: "Spielsteuerung",
      pauseTitle: "Pause",
      pauseText: "Verwenden Sie die Pause-Schaltfläche für Pausen. Der Spielbildschirm wird unscharf und Timer werden gestoppt.",
      editorTitle: "Editor",
      editorText: "Sie können jede Frage direkt vor dem Spiel ändern. Änderungen werden nur für die aktuelle Sitzung gespeichert.",
      exportTitle: "Export",
      exportText: "Klicken Sie auf das Speichersymbol in der Bibliothek, um einen Satz auf die Festplatte zu laden.",
      section04Title: "Spieleinstellungen",
      section04Desc: "Alle Einstellungen werden auf dem Startbildschirm vorgenommen.",
      settingsMode: "Spielmodus",
      settingsModeWithQ: "Mit Fragen",
      settingsModeWithQDesc: "Klassischer Modus: nach jedem Paar — eine Bonusfrage für Extrapunkte.",
      settingsModeMemory: "Nur Memory",
      settingsModeMemoryDesc: "Reines Gedächtnisspiel ohne Quiz.",
      settingsSuite: "Fragensatz",
      settingsSuiteDesc: "Wählen Sie den aktiven Satz aus der Bibliothek.",
      settingsTeams: "Teams",
      settingsTeamsDesc: "2–5 Teams. Benennen Sie jedes Team (bis zu 20 Zeichen).",
      settingsTimers: "Timer",
      settingsTimerFlip: "Paarsuche",
      settingsTimerFlipDesc: "5–60 Sek. Zeit, in der umgedrehte Karten sichtbar bleiben.",
      settingsTimerLevel: "Schwierigkeitswahl",
      settingsTimerLevelDesc: "3–30 Sek. Zeit zur Wahl der Bonusfragenschwierigkeit.",
      settingsTimerAnswer: "Antwortzeit",
      settingsTimerAnswerDesc: "10–120 Sek. Zeit zum Besprechen und Antworten.",
      settingsStartTip: "Tipp: Versuchen Sie beim ersten Spiel den Modus 'Nur Memory'.",
      footerVersion: "v2.6 Stable / No-Flag Locale Engine",
      footerTagline: "\"Alphabet\" — ein intellektuelles Spiel zum Lernen und Wachsen.",
    },
    close: "Schließen",
    promptPageTitle: "Prompt-Generator",
    promptPageDesc: "Vorlage für die mehrsprachige Generierung komplexer Bibelquiz-Fragen in KI-Chatbots.",
    promptPageCopy: "KOPIEREN",
    promptPageCopied: "Prompt kopiert!",
    title: "ALPHABET",
    subtitle: "Intellektuelles Bibelquiz.",
    start: "SPIEL STARTEN",
    settings: "Spieleinstellungen",
    mode: "Spielmodus",
    withQuestions: "MIT FRAGEN",
    withoutQuestions: "NUR MEMORY",
    teamsCount: "Anzahl der Teams",
    teamNames: "Teamnamen",
    activeSuite: "Aktives Set",
    change: "Ändern",
    timers: "Timer",
    flipTimer: "Paare suchen (Sek)",
    levelTimer: "Schwierigkeit (Sek)",
    answerTimerLabel: "Antwort (Sek)",
    aiGenerator: "KI-GENERATOR",
    library: "BIBLIOTHEK",
    importJson: "JSON IMPORTIEREN",
    guide: "ANLEITUNG",
    prompt: "KI-PROMPT",
    rules: "Spielregeln",
    pause: "PAUSE",
    resume: "FORTSETZEN",
    finish: "BEENDEN",
    turnOf: "AKTUELLER ZUG",
    team: "TEAM",
    progress: "FORTSCHRITT",
    correct: "RICHTIG!",
    wrong: "FALSCH!",
    rightAnswer: "Richtige Antwort",
    check: "PRÜFEN",
    points: "Punkte",
    victoryTitle: "Quiz beendet!",
    leaderboard: "Abschlusstabelle",
    mainMenu: "HAUPTMENÜ",
    back: "ZURÜCK",
    home: "HOME",
    complexity: {
      easy: "Leicht",
      medium: "Mittel",
      hard: "Schwer"
    },
    levelFinished: "Keine weiteren Fragen",
    allQuestionsFinished: "Es gibt keine weiteren Fragen in diesem Set!",
    notSelected: "Nicht ausgewählt",
    newSuite: "Neues Frageset",
    defaultTopic: "Biblische Figuren",
    suiteLoaded: (title: string) => `Set «${title}» erfolgreich geladen und aktiviert!`,
    invalidJson: "Fehler: Ungültiges JSON-Format",
    fileReadError: "Fehler beim Lesen der Datei",
    turnTransition: "ZUG GEHT AN",
    chooseLevel: "Wähle Schwierigkeit!",
    remaining: "Verbleibend: ",
    timeoutHint: "Wenn die Zeit abläuft, wird ein verfügbares Level gewählt.",
  },
  ro: {
    rulesPage: {
      title: "Regulile Jocului",
      subtitle: "Inteligență • Memorie",
      section01Title: "Scopul Jocului",
      section01Text: (cardCount: number, pairCount: number) =>
        `Jocul combină mecanica clasică de antrenament al memoriei cu un quiz biblic aprofundat. Tabla are ${cardCount} cărți cu ${pairCount} perechi de litere. Scopul tău este să găsești cât mai multe perechi și să acumulezi puncte prin răspunsuri corecte la întrebările bonus.`,
      section02Title: "Mecanica Turului",
      section02Intro: "Echipele joacă pe rând. În turul lor, o echipă întoarce două cărți.",
      matchTitle: "POTRIVIRE:",
      matchItem1: (n: number) => `Scorul crește cu +${n} puncte.`,
      matchItem2: "Cărțile rămân descoperite.",
      matchItem3: "Echipa primește o ÎNTREBARE BONUS.",
      matchItem4: "Turul rămâne la aceeași echipă!",
      missTitle: "RATARE:",
      missItem1: "Cărțile se întorc după 1 secundă.",
      missItem2: "Nu se acordă puncte.",
      missItem3: "Turul trece la echipa următoare.",
      section03Title: "Sistem de Punctaj",
      tableAction: "Acțiune",
      tableReward: "Recompensă",
      rowMatch: "Pereche de litere găsită",
      rowMatchPoints: (n: number) => `+${n} puncte`,
      rowEasy: "Întrebare bonus: UȘOR",
      rowEasyPoints: (n: number) => `+${n} puncte`,
      rowMedium: "Întrebare bonus: MEDIU",
      rowMediumPoints: (n: number) => `+${n} puncte`,
      rowHard: "Întrebare bonus: GREU",
      rowHardPoints: (n: number) => `+${n} puncte`,
      section04Title: "Întrebări Bonus",
      section04Text: "După găsirea unei perechi, echipa are șansa de a-și mări avantajul. Moderatorul oferă trei niveluri de dificultate.",
      section04Note: "Notă: Echipele au 5–10 secunde să aleagă dificultatea. Dacă timpul expiră, se selectează automat UȘOR. Răspunsurile greșite nu costă puncte, dar echipa pierde bonusul.",
      finishTitle: "Finalul Jocului",
      finishText: "Jocul continuă până când toate cărțile de pe tablă sunt descoperite. Câștigă echipa cu cel mai mare scor total (perechi + bonusuri).",
      mainMenuBtn: "MENIU PRINCIPAL",
      openGuide: "Deschide ghidul operatorului",
    },
    guidePage: {
      title: "Ghidul Operatorului",
      version: "v2.6 • Bibliotecă",
      grokTitle: "Generarea Întrebărilor",
      grokBadge: "PRO TIP",
      grokText: "Pentru a crea seturi unice de întrebări, recomandăm cu tărie Grok AI. Este un instrument dovedit care înțelege bine sarcina.",
      grokSaveHint: "Cum să salvați rezultatul:",
      grokSaveText: (ext: string) => `Copiați textul generat de IA într-un editor de text și salvați fișierul ca mygame${ext}. Important: adăugați extensia ${ext} la sfârșitul numelui fișierului.`,
      grokOpenBtn: "Deschide Grok.com",
      grokPromptBtn: "Obține Șablonul de Prompt",
      section01Title: "Generare și Limbi",
      multiTitle: "Multilingv:",
      multiText: "Aplicația suportă RU, EN, UK, DE, RO. Locala setului este afișată ca cod text.",
      multiTip: "Sfat: La generarea în engleză, introduceți tema tot în engleză pentru rezultate mai bune.",
      aiTitle: "Controale IA:",
      aiText: "Puteți opri generarea în orice moment dacă observați o greșeală în temă sau ați selectat limba greșită.",
      aiBullet1: "Rezolvați CAPTCHA pentru a confirma startul",
      aiBullet2: "150 întrebări oferă o varietate enormă",
      section02Title: "Biblioteca de Seturi",
      systemTitle: "Seturi de Sistem (SYSTEM)",
      systemText: "Acesta este standardul de aur al jocului. Seturile pentru Regi, Faptele Apostolilor și Proverbe sunt întotdeauna disponibile și nu pot fi șterse.",
      systemNote: "NOTĂ: Puteți edita întrebările dintr-un set de sistem în sesiunea curentă, dar după reîncărcare revine la starea originală.",
      userTitle: "Seturi Utilizator (USER)",
      userText: "Seturi create prin IA sau importate din fișiere JSON. Sunt stocate în browser până când le ștergeți.",
      section03Title: "Controale Joc",
      pauseTitle: "Pauză",
      pauseText: "Folosiți butonul de pauză pentru pauze. Ecranul jocului va fi estompat, iar cronometrele se vor opri.",
      editorTitle: "Editor",
      editorText: "Puteți modifica orice întrebare chiar înainte de joc. Modificările sunt salvate doar pentru sesiunea curentă.",
      exportTitle: "Export",
      exportText: "Faceți clic pe pictograma de salvare din bibliotecă pentru a descărca un set pe disc.",
      section04Title: "Setările Jocului",
      section04Desc: "Toate setările se configurează pe ecranul de pornire.",
      settingsMode: "Modul de joc",
      settingsModeWithQ: "Cu întrebări",
      settingsModeWithQDesc: "Modul clasic: după fiecare pereche — o întrebare bonus pentru puncte suplimentare.",
      settingsModeMemory: "Doar Memory",
      settingsModeMemoryDesc: "Joc de memorie pur, fără quiz.",
      settingsSuite: "Set de întrebări",
      settingsSuiteDesc: "Selectați setul activ din Bibliotecă.",
      settingsTeams: "Echipe",
      settingsTeamsDesc: "2–5 echipe. Numiți fiecare echipă (până la 20 de caractere).",
      settingsTimers: "Cronometre",
      settingsTimerFlip: "Căutare perechi",
      settingsTimerFlipDesc: "5–60 sec. Timp în care cărțile întoarse rămân vizibile.",
      settingsTimerLevel: "Alegere dificultate",
      settingsTimerLevelDesc: "3–30 sec. Timp pentru alegerea dificultății întrebării bonus.",
      settingsTimerAnswer: "Timp de răspuns",
      settingsTimerAnswerDesc: "10–120 sec. Timp pentru discuție și răspuns.",
      settingsStartTip: "Sfat: La primul joc, încercați modul 'Doar Memory'.",
      footerVersion: "v2.6 Stable / No-Flag Locale Engine",
      footerTagline: "\"Alfabet\" — un joc intelectual pentru învățare și creștere.",
    },
    close: "Închide",
    promptPageTitle: "Generator de Prompt",
    promptPageDesc: "Șablon pentru generarea multilingvă a întrebărilor complexe în chatboți AI.",
    promptPageCopy: "COPIAȚI",
    promptPageCopied: "Prompt copiat!",
    title: "ALFABET",
    subtitle: "Quiz Biblic Interactiv.",
    start: "ÎNCEPE JOCUL",
    settings: "Setările jocului",
    mode: "Modul de joc",
    withQuestions: "CU ÎNTREBĂRI",
    withoutQuestions: "DOAR MEMORY",
    teamsCount: "Numărul de echipe",
    teamNames: "Numele echipelor",
    activeSuite: "Set activ",
    change: "Schimbă",
    timers: "Timere",
    flipTimer: "Căutare perechi (sec)",
    levelTimer: "Dificultate (sec)",
    answerTimerLabel: "Răspuns (sec)",
    aiGenerator: "GENERATOR AI",
    library: "BIBLIOTECĂ",
    importJson: "IMPORTĂ JSON",
    guide: "GHID",
    prompt: "PROMPT AI",
    rules: "Regulile jocului",
    pause: "PAUZĂ",
    resume: "CONTINUĂ",
    finish: "TERMINĂ",
    turnOf: "RÂNDUL ECHIPEI",
    team: "ECHIPĂ",
    progress: "PROGRES",
    correct: "CORECT!",
    wrong: "GREȘIT!",
    rightAnswer: "Răspuns corect",
    check: "VERIFICĂ",
    points: "puncte",
    victoryTitle: "Finala quiz-ului!",
    leaderboard: "Clasament final",
    mainMenu: "MENIU PRINCIPAL",
    back: "ÎNAPOI",
    home: "ACASĂ",
    complexity: {
      easy: "Ușor",
      medium: "Mediu",
      hard: "Greu"
    },
    levelFinished: "Nu mai sunt întrebări",
    allQuestionsFinished: "Nu mai sunt întrebări în acest set!",
    notSelected: "Neselectat",
    newSuite: "Set nou de întrebări",
    defaultTopic: "Personaje biblice",
    suiteLoaded: (title: string) => `Setul «${title}» a fost încărcat și activat!`,
    invalidJson: "Eroare: Format JSON invalid",
    fileReadError: "Eroare la citirea fișierului",
    turnTransition: "RÂNDUL TRECE LA",
    chooseLevel: "Alege dificultatea!",
    remaining: "Rămase: ",
    timeoutHint: "Dacă timpul expiră, va fi ales un nivel disponibil.",
  },
};

export const COLORS = {
  primary: "#1e3a8a", 
  secondary: "#fbbf24", 
  accent: "#ef4444", 
  success: "#10b981", 
  background: "#f8fafc", 
};

export const SCORE_MATCH = 5;
export const SCORE_EASY = 3;
export const SCORE_MEDIUM = 6;
export const SCORE_HARD = 10;
